name: tabbed_scaffold
description: A `Scaffold`-like widget tailored for tab-bar navigation.
version: 0.0.1
author: Juan Diego Fajardo <jfajardo200@gmail.com>
homepage: https://github.com/kuanfajardo/tabbed_scaffold.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  copier: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: